(cl:in-package sixwd_msgs-msg)
(cl:export '(LINEARSPEED-VAL
          LINEARSPEED
          MOTOR1_SPEED-VAL
          MOTOR1_SPEED
          MOTOR2_SPEED-VAL
          MOTOR2_SPEED
          MOTOR3_SPEED-VAL
          MOTOR3_SPEED
          MOTOR4_SPEED-VAL
          MOTOR4_SPEED
          MOTOR5_SPEED-VAL
          MOTOR5_SPEED
          MOTOR6_SPEED-VAL
          MOTOR6_SPEED
          MOTOR1_CURRENT-VAL
          MOTOR1_CURRENT
          MOTOR2_CURRENT-VAL
          MOTOR2_CURRENT
          MOTOR3_CURRENT-VAL
          MOTOR3_CURRENT
          MOTOR4_CURRENT-VAL
          MOTOR4_CURRENT
          MOTOR5_CURRENT-VAL
          MOTOR5_CURRENT
          MOTOR6_CURRENT-VAL
          MOTOR6_CURRENT
          VOLTAGE-VAL
          VOLTAGE
          TEMPERATURE-VAL
          TEMPERATURE
))