//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the wallfollowing1 package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __wallfollowing1__WALLFOLLOWING1CONFIG_H__
#define __wallfollowing1__WALLFOLLOWING1CONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace wallfollowing1
{
  class wallfollowing1ConfigStatics;

  class wallfollowing1Config
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(wallfollowing1Config &config, const wallfollowing1Config &max, const wallfollowing1Config &min) const = 0;
      virtual void calcLevel(uint32_t &level, const wallfollowing1Config &config1, const wallfollowing1Config &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, wallfollowing1Config &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const wallfollowing1Config &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, wallfollowing1Config &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const wallfollowing1Config &config) const = 0;
      virtual void getValue(const wallfollowing1Config &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T wallfollowing1Config::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (wallfollowing1Config::* field);

      virtual void clamp(wallfollowing1Config &config, const wallfollowing1Config &max, const wallfollowing1Config &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const wallfollowing1Config &config1, const wallfollowing1Config &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, wallfollowing1Config &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const wallfollowing1Config &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, wallfollowing1Config &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const wallfollowing1Config &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const wallfollowing1Config &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, wallfollowing1Config &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, wallfollowing1Config &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<wallfollowing1Config::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(wallfollowing1Config &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("fallback_range"==(*_i)->name){fallback_range = boost::any_cast<double>(val);}
        if("sample_angle_1"==(*_i)->name){sample_angle_1 = boost::any_cast<double>(val);}
        if("sample_angle_2"==(*_i)->name){sample_angle_2 = boost::any_cast<double>(val);}
        if("wall_following_max_speed"==(*_i)->name){wall_following_max_speed = boost::any_cast<double>(val);}
        if("wall_following_min_speed"==(*_i)->name){wall_following_min_speed = boost::any_cast<double>(val);}
        if("prediction_distance"==(*_i)->name){prediction_distance = boost::any_cast<double>(val);}
        if("target_wall_distance"==(*_i)->name){target_wall_distance = boost::any_cast<double>(val);}
        if("time_between_scans"==(*_i)->name){time_between_scans = boost::any_cast<double>(val);}
      }
    }

    double fallback_range;
double sample_angle_1;
double sample_angle_2;
double wall_following_max_speed;
double wall_following_min_speed;
double prediction_distance;
double target_wall_distance;
double time_between_scans;

    bool state;
    std::string name;

    class VALID_LIDAR_MEASUREMENT_RANGE
{
  public:
    VALID_LIDAR_MEASUREMENT_RANGE()
    {
      state = true;
      name = "Valid_lidar_measurement_range";
    }

    void setParams(wallfollowing1Config &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("min_range"==(*_i)->name){min_range = boost::any_cast<double>(val);}
        if("max_range"==(*_i)->name){max_range = boost::any_cast<double>(val);}
      }
    }

    double min_range;
double max_range;

    bool state;
    std::string name;

    
}valid_lidar_measurement_range;

}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double fallback_range;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sample_angle_1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sample_angle_2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wall_following_max_speed;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wall_following_min_speed;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double prediction_distance;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double target_wall_distance;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double time_between_scans;
//#line 9 "/home/karel/Documents/University/WS2019/AAIP/software_integration/src/autonomous/wallfollowing1/cfg/wallfollowing1.cfg"
      double min_range;
//#line 10 "/home/karel/Documents/University/WS2019/AAIP/software_integration/src/autonomous/wallfollowing1/cfg/wallfollowing1.cfg"
      double max_range;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("wallfollowing1Config::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const wallfollowing1Config &__max__ = __getMax__();
      const wallfollowing1Config &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const wallfollowing1Config &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const wallfollowing1Config &__getDefault__();
    static const wallfollowing1Config &__getMax__();
    static const wallfollowing1Config &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const wallfollowing1ConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void wallfollowing1Config::ParamDescription<std::string>::clamp(wallfollowing1Config &config, const wallfollowing1Config &max, const wallfollowing1Config &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class wallfollowing1ConfigStatics
  {
    friend class wallfollowing1Config;

    wallfollowing1ConfigStatics()
    {
wallfollowing1Config::GroupDescription<wallfollowing1Config::DEFAULT, wallfollowing1Config> Default("Default", "", 0, 0, true, &wallfollowing1Config::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.fallback_range = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.fallback_range = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.fallback_range = 4.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("fallback_range", "double", 0, "Fallback range in case no valid LIDAR range was found.", "", &wallfollowing1Config::fallback_range)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("fallback_range", "double", 0, "Fallback range in case no valid LIDAR range was found.", "", &wallfollowing1Config::fallback_range)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sample_angle_1 = -std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sample_angle_1 = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sample_angle_1 = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("sample_angle_1", "double", 0, "The first steering_cmd to sample a point on the wall.", "", &wallfollowing1Config::sample_angle_1)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("sample_angle_1", "double", 0, "The first steering_cmd to sample a point on the wall.", "", &wallfollowing1Config::sample_angle_1)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sample_angle_2 = -std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sample_angle_2 = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sample_angle_2 = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("sample_angle_2", "double", 0, "The second steering_cmd to sample a point on the wall.", "", &wallfollowing1Config::sample_angle_2)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("sample_angle_2", "double", 0, "The second steering_cmd to sample a point on the wall.", "", &wallfollowing1Config::sample_angle_2)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wall_following_max_speed = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wall_following_max_speed = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wall_following_max_speed = 0.25;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("wall_following_max_speed", "double", 0, "Specifies the maximum speed.", "", &wallfollowing1Config::wall_following_max_speed)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("wall_following_max_speed", "double", 0, "Specifies the maximum speed.", "", &wallfollowing1Config::wall_following_max_speed)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wall_following_min_speed = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wall_following_min_speed = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wall_following_min_speed = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("wall_following_min_speed", "double", 0, "Specifies the minimum speed.", "", &wallfollowing1Config::wall_following_min_speed)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("wall_following_min_speed", "double", 0, "Specifies the minimum speed.", "", &wallfollowing1Config::wall_following_min_speed)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.prediction_distance = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.prediction_distance = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.prediction_distance = 2.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("prediction_distance", "double", 0, "The car will aim to reach the target wall distance after travelling this distance. The higher this number, the more aggressively the car will cut corners.", "", &wallfollowing1Config::prediction_distance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("prediction_distance", "double", 0, "The car will aim to reach the target wall distance after travelling this distance. The higher this number, the more aggressively the car will cut corners.", "", &wallfollowing1Config::prediction_distance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.target_wall_distance = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.target_wall_distance = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.target_wall_distance = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("target_wall_distance", "double", 0, "The desired distance between the wall and the car.", "", &wallfollowing1Config::target_wall_distance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("target_wall_distance", "double", 0, "The desired distance between the wall and the car.", "", &wallfollowing1Config::target_wall_distance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.time_between_scans = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.time_between_scans = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.time_between_scans = 0.025;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("time_between_scans", "double", 0, "TODO Tooltip", "", &wallfollowing1Config::time_between_scans)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("time_between_scans", "double", 0, "TODO Tooltip", "", &wallfollowing1Config::time_between_scans)));
wallfollowing1Config::GroupDescription<wallfollowing1Config::DEFAULT::VALID_LIDAR_MEASUREMENT_RANGE, wallfollowing1Config::DEFAULT> Valid_lidar_measurement_range("Valid_lidar_measurement_range", "", 0, 1, true, &wallfollowing1Config::DEFAULT::valid_lidar_measurement_range);
//#line 9 "/home/karel/Documents/University/WS2019/AAIP/software_integration/src/autonomous/wallfollowing1/cfg/wallfollowing1.cfg"
      __min__.min_range = 0.0;
//#line 9 "/home/karel/Documents/University/WS2019/AAIP/software_integration/src/autonomous/wallfollowing1/cfg/wallfollowing1.cfg"
      __max__.min_range = std::numeric_limits<double>::infinity();
//#line 9 "/home/karel/Documents/University/WS2019/AAIP/software_integration/src/autonomous/wallfollowing1/cfg/wallfollowing1.cfg"
      __default__.min_range = 0.2;
//#line 9 "/home/karel/Documents/University/WS2019/AAIP/software_integration/src/autonomous/wallfollowing1/cfg/wallfollowing1.cfg"
      Valid_lidar_measurement_range.abstract_parameters.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("min_range", "double", 0, "Discards LIDAR measurements below this range.", "", &wallfollowing1Config::min_range)));
//#line 9 "/home/karel/Documents/University/WS2019/AAIP/software_integration/src/autonomous/wallfollowing1/cfg/wallfollowing1.cfg"
      __param_descriptions__.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("min_range", "double", 0, "Discards LIDAR measurements below this range.", "", &wallfollowing1Config::min_range)));
//#line 10 "/home/karel/Documents/University/WS2019/AAIP/software_integration/src/autonomous/wallfollowing1/cfg/wallfollowing1.cfg"
      __min__.max_range = 0.0;
//#line 10 "/home/karel/Documents/University/WS2019/AAIP/software_integration/src/autonomous/wallfollowing1/cfg/wallfollowing1.cfg"
      __max__.max_range = std::numeric_limits<double>::infinity();
//#line 10 "/home/karel/Documents/University/WS2019/AAIP/software_integration/src/autonomous/wallfollowing1/cfg/wallfollowing1.cfg"
      __default__.max_range = 30.0;
//#line 10 "/home/karel/Documents/University/WS2019/AAIP/software_integration/src/autonomous/wallfollowing1/cfg/wallfollowing1.cfg"
      Valid_lidar_measurement_range.abstract_parameters.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("max_range", "double", 0, "Discards LIDAR measurements above this range.", "", &wallfollowing1Config::max_range)));
//#line 10 "/home/karel/Documents/University/WS2019/AAIP/software_integration/src/autonomous/wallfollowing1/cfg/wallfollowing1.cfg"
      __param_descriptions__.push_back(wallfollowing1Config::AbstractParamDescriptionConstPtr(new wallfollowing1Config::ParamDescription<double>("max_range", "double", 0, "Discards LIDAR measurements above this range.", "", &wallfollowing1Config::max_range)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Valid_lidar_measurement_range.convertParams();
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(wallfollowing1Config::AbstractGroupDescriptionConstPtr(new wallfollowing1Config::GroupDescription<wallfollowing1Config::DEFAULT::VALID_LIDAR_MEASUREMENT_RANGE, wallfollowing1Config::DEFAULT>(Valid_lidar_measurement_range)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(wallfollowing1Config::AbstractGroupDescriptionConstPtr(new wallfollowing1Config::GroupDescription<wallfollowing1Config::DEFAULT::VALID_LIDAR_MEASUREMENT_RANGE, wallfollowing1Config::DEFAULT>(Valid_lidar_measurement_range)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(wallfollowing1Config::AbstractGroupDescriptionConstPtr(new wallfollowing1Config::GroupDescription<wallfollowing1Config::DEFAULT, wallfollowing1Config>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<wallfollowing1Config::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<wallfollowing1Config::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<wallfollowing1Config::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    wallfollowing1Config __max__;
    wallfollowing1Config __min__;
    wallfollowing1Config __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const wallfollowing1ConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static wallfollowing1ConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &wallfollowing1Config::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const wallfollowing1Config &wallfollowing1Config::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const wallfollowing1Config &wallfollowing1Config::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const wallfollowing1Config &wallfollowing1Config::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<wallfollowing1Config::AbstractParamDescriptionConstPtr> &wallfollowing1Config::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<wallfollowing1Config::AbstractGroupDescriptionConstPtr> &wallfollowing1Config::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const wallfollowing1ConfigStatics *wallfollowing1Config::__get_statics__()
  {
    const static wallfollowing1ConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = wallfollowing1ConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __WALLFOLLOWING1RECONFIGURATOR_H__
