//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the wallfollowing2 package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __wallfollowing2__WALLFOLLOWING2CONFIG_H__
#define __wallfollowing2__WALLFOLLOWING2CONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace wallfollowing2
{
  class wallfollowing2ConfigStatics;

  class wallfollowing2Config
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(wallfollowing2Config &config, const wallfollowing2Config &max, const wallfollowing2Config &min) const = 0;
      virtual void calcLevel(uint32_t &level, const wallfollowing2Config &config1, const wallfollowing2Config &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, wallfollowing2Config &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const wallfollowing2Config &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, wallfollowing2Config &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const wallfollowing2Config &config) const = 0;
      virtual void getValue(const wallfollowing2Config &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T wallfollowing2Config::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (wallfollowing2Config::* field);

      virtual void clamp(wallfollowing2Config &config, const wallfollowing2Config &max, const wallfollowing2Config &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const wallfollowing2Config &config1, const wallfollowing2Config &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, wallfollowing2Config &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const wallfollowing2Config &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, wallfollowing2Config &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const wallfollowing2Config &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const wallfollowing2Config &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, wallfollowing2Config &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, wallfollowing2Config &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<wallfollowing2Config::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(wallfollowing2Config &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("min_throttle"==(*_i)->name){min_throttle = boost::any_cast<double>(val);}
        if("max_throttle"==(*_i)->name){max_throttle = boost::any_cast<double>(val);}
        if("radius_lower"==(*_i)->name){radius_lower = boost::any_cast<double>(val);}
        if("radius_upper"==(*_i)->name){radius_upper = boost::any_cast<double>(val);}
        if("steering_slow_down"==(*_i)->name){steering_slow_down = boost::any_cast<double>(val);}
        if("steering_slow_down_dead_zone"==(*_i)->name){steering_slow_down_dead_zone = boost::any_cast<double>(val);}
        if("high_speed_steering_limit"==(*_i)->name){high_speed_steering_limit = boost::any_cast<double>(val);}
        if("high_speed_steering_limit_dead_zone"==(*_i)->name){high_speed_steering_limit_dead_zone = boost::any_cast<double>(val);}
        if("max_acceleration"==(*_i)->name){max_acceleration = boost::any_cast<double>(val);}
        if("corner_cutting"==(*_i)->name){corner_cutting = boost::any_cast<double>(val);}
        if("straight_smoothing"==(*_i)->name){straight_smoothing = boost::any_cast<double>(val);}
        if("barrier_size_realtive"==(*_i)->name){barrier_size_realtive = boost::any_cast<double>(val);}
        if("barrier_lower_limit"==(*_i)->name){barrier_lower_limit = boost::any_cast<double>(val);}
        if("barrier_upper_limit"==(*_i)->name){barrier_upper_limit = boost::any_cast<double>(val);}
        if("barrier_exponent"==(*_i)->name){barrier_exponent = boost::any_cast<double>(val);}
        if("controller_p"==(*_i)->name){controller_p = boost::any_cast<double>(val);}
        if("controller_i"==(*_i)->name){controller_i = boost::any_cast<double>(val);}
        if("controller_d"==(*_i)->name){controller_d = boost::any_cast<double>(val);}
        if("usable_laser_range"==(*_i)->name){usable_laser_range = boost::any_cast<double>(val);}
      }
    }

    double min_throttle;
double max_throttle;
double radius_lower;
double radius_upper;
double steering_slow_down;
double steering_slow_down_dead_zone;
double high_speed_steering_limit;
double high_speed_steering_limit_dead_zone;
double max_acceleration;
double corner_cutting;
double straight_smoothing;
double barrier_size_realtive;
double barrier_lower_limit;
double barrier_upper_limit;
double barrier_exponent;
double controller_p;
double controller_i;
double controller_d;
double usable_laser_range;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_throttle;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_throttle;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double radius_lower;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double radius_upper;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double steering_slow_down;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double steering_slow_down_dead_zone;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double high_speed_steering_limit;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double high_speed_steering_limit_dead_zone;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_acceleration;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double corner_cutting;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double straight_smoothing;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double barrier_size_realtive;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double barrier_lower_limit;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double barrier_upper_limit;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double barrier_exponent;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double controller_p;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double controller_i;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double controller_d;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double usable_laser_range;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("wallfollowing2Config::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const wallfollowing2Config &__max__ = __getMax__();
      const wallfollowing2Config &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const wallfollowing2Config &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const wallfollowing2Config &__getDefault__();
    static const wallfollowing2Config &__getMax__();
    static const wallfollowing2Config &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const wallfollowing2ConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void wallfollowing2Config::ParamDescription<std::string>::clamp(wallfollowing2Config &config, const wallfollowing2Config &max, const wallfollowing2Config &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class wallfollowing2ConfigStatics
  {
    friend class wallfollowing2Config;

    wallfollowing2ConfigStatics()
    {
wallfollowing2Config::GroupDescription<wallfollowing2Config::DEFAULT, wallfollowing2Config> Default("Default", "", 0, 0, true, &wallfollowing2Config::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_throttle = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_throttle = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_throttle = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("min_throttle", "double", 0, "Specifies the minimum speed.", "", &wallfollowing2Config::min_throttle)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("min_throttle", "double", 0, "Specifies the minimum speed.", "", &wallfollowing2Config::min_throttle)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_throttle = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_throttle = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_throttle = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("max_throttle", "double", 0, "Specifies the maximum speed.", "", &wallfollowing2Config::max_throttle)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("max_throttle", "double", 0, "Specifies the maximum speed.", "", &wallfollowing2Config::max_throttle)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.radius_lower = 0.001;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.radius_lower = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.radius_lower = 2.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("radius_lower", "double", 0, "Specifies a lower radius, used to calculate a speed limit.", "", &wallfollowing2Config::radius_lower)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("radius_lower", "double", 0, "Specifies a lower radius, used to calculate a speed limit.", "", &wallfollowing2Config::radius_lower)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.radius_upper = 0.001;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.radius_upper = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.radius_upper = 30.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("radius_upper", "double", 0, "Specifies a upper radius, used to calculate a speed limit.", "", &wallfollowing2Config::radius_upper)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("radius_upper", "double", 0, "Specifies a upper radius, used to calculate a speed limit.", "", &wallfollowing2Config::radius_upper)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.steering_slow_down = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.steering_slow_down = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.steering_slow_down = 4.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("steering_slow_down", "double", 0, "Used to calculate the speed limit error.", "", &wallfollowing2Config::steering_slow_down)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("steering_slow_down", "double", 0, "Used to calculate the speed limit error.", "", &wallfollowing2Config::steering_slow_down)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.steering_slow_down_dead_zone = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.steering_slow_down_dead_zone = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.steering_slow_down_dead_zone = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("steering_slow_down_dead_zone", "double", 0, "Used to calculate the speed limit error.", "", &wallfollowing2Config::steering_slow_down_dead_zone)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("steering_slow_down_dead_zone", "double", 0, "Used to calculate the speed limit error.", "", &wallfollowing2Config::steering_slow_down_dead_zone)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.high_speed_steering_limit = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.high_speed_steering_limit = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.high_speed_steering_limit = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("high_speed_steering_limit", "double", 0, "Used to calculate the steering steering_cmd.", "", &wallfollowing2Config::high_speed_steering_limit)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("high_speed_steering_limit", "double", 0, "Used to calculate the steering steering_cmd.", "", &wallfollowing2Config::high_speed_steering_limit)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.high_speed_steering_limit_dead_zone = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.high_speed_steering_limit_dead_zone = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.high_speed_steering_limit_dead_zone = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("high_speed_steering_limit_dead_zone", "double", 0, "Used to calculate the steering steering_cmd.", "", &wallfollowing2Config::high_speed_steering_limit_dead_zone)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("high_speed_steering_limit_dead_zone", "double", 0, "Used to calculate the steering steering_cmd.", "", &wallfollowing2Config::high_speed_steering_limit_dead_zone)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_acceleration = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_acceleration = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_acceleration = 0.4;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("max_acceleration", "double", 0, "Specifies the maximum acceleration.", "", &wallfollowing2Config::max_acceleration)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("max_acceleration", "double", 0, "Specifies the maximum acceleration.", "", &wallfollowing2Config::max_acceleration)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.corner_cutting = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.corner_cutting = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.corner_cutting = 1.4;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("corner_cutting", "double", 0, "Used to calculate the predicted car position.", "", &wallfollowing2Config::corner_cutting)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("corner_cutting", "double", 0, "Used to calculate the predicted car position.", "", &wallfollowing2Config::corner_cutting)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.straight_smoothing = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.straight_smoothing = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.straight_smoothing = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("straight_smoothing", "double", 0, "Used to calculate the predicted car position.", "", &wallfollowing2Config::straight_smoothing)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("straight_smoothing", "double", 0, "Used to calculate the predicted car position.", "", &wallfollowing2Config::straight_smoothing)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.barrier_size_realtive = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.barrier_size_realtive = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.barrier_size_realtive = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("barrier_size_realtive", "double", 0, "Used to calculate the start and end point of the barrier. The barrier is the distance the car can drive straight.", "", &wallfollowing2Config::barrier_size_realtive)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("barrier_size_realtive", "double", 0, "Used to calculate the start and end point of the barrier. The barrier is the distance the car can drive straight.", "", &wallfollowing2Config::barrier_size_realtive)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.barrier_lower_limit = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.barrier_lower_limit = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.barrier_lower_limit = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("barrier_lower_limit", "double", 0, "Used to calulate the speed limit at the end of straight track sections.", "", &wallfollowing2Config::barrier_lower_limit)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("barrier_lower_limit", "double", 0, "Used to calulate the speed limit at the end of straight track sections.", "", &wallfollowing2Config::barrier_lower_limit)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.barrier_upper_limit = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.barrier_upper_limit = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.barrier_upper_limit = 15.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("barrier_upper_limit", "double", 0, "Used to calulate the speed limit at the end of straight track sections.", "", &wallfollowing2Config::barrier_upper_limit)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("barrier_upper_limit", "double", 0, "Used to calulate the speed limit at the end of straight track sections.", "", &wallfollowing2Config::barrier_upper_limit)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.barrier_exponent = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.barrier_exponent = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.barrier_exponent = 1.4;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("barrier_exponent", "double", 0, "Used to calulate the speed limit at the end of straight track sections.", "", &wallfollowing2Config::barrier_exponent)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("barrier_exponent", "double", 0, "Used to calulate the speed limit at the end of straight track sections.", "", &wallfollowing2Config::barrier_exponent)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.controller_p = -std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.controller_p = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.controller_p = 4.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("controller_p", "double", 0, "Specifies the proportional value of the PID controller.", "", &wallfollowing2Config::controller_p)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("controller_p", "double", 0, "Specifies the proportional value of the PID controller.", "", &wallfollowing2Config::controller_p)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.controller_i = -std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.controller_i = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.controller_i = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("controller_i", "double", 0, "Specifies the integral value of the PID controller.", "", &wallfollowing2Config::controller_i)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("controller_i", "double", 0, "Specifies the integral value of the PID controller.", "", &wallfollowing2Config::controller_i)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.controller_d = -std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.controller_d = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.controller_d = 0.02;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("controller_d", "double", 0, "Specifies the derivative value of the PID controller.", "", &wallfollowing2Config::controller_d)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("controller_d", "double", 0, "Specifies the derivative value of the PID controller.", "", &wallfollowing2Config::controller_d)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.usable_laser_range = 90.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.usable_laser_range = 271.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.usable_laser_range = 220.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("usable_laser_range", "double", 0, "The size of the part of the laser scan that should be used by the algorithm, in degrees.", "", &wallfollowing2Config::usable_laser_range)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(wallfollowing2Config::AbstractParamDescriptionConstPtr(new wallfollowing2Config::ParamDescription<double>("usable_laser_range", "double", 0, "The size of the part of the laser scan that should be used by the algorithm, in degrees.", "", &wallfollowing2Config::usable_laser_range)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(wallfollowing2Config::AbstractGroupDescriptionConstPtr(new wallfollowing2Config::GroupDescription<wallfollowing2Config::DEFAULT, wallfollowing2Config>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<wallfollowing2Config::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<wallfollowing2Config::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<wallfollowing2Config::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    wallfollowing2Config __max__;
    wallfollowing2Config __min__;
    wallfollowing2Config __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const wallfollowing2ConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static wallfollowing2ConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &wallfollowing2Config::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const wallfollowing2Config &wallfollowing2Config::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const wallfollowing2Config &wallfollowing2Config::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const wallfollowing2Config &wallfollowing2Config::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<wallfollowing2Config::AbstractParamDescriptionConstPtr> &wallfollowing2Config::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<wallfollowing2Config::AbstractGroupDescriptionConstPtr> &wallfollowing2Config::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const wallfollowing2ConfigStatics *wallfollowing2Config::__get_statics__()
  {
    const static wallfollowing2ConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = wallfollowing2ConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __WALLFOLLOWING2RECONFIGURATOR_H__
