// Generated by gencpp from file reinforcement_learning/EpisodeResult.msg
// DO NOT EDIT!


#ifndef REINFORCEMENT_LEARNING_MESSAGE_EPISODERESULT_H
#define REINFORCEMENT_LEARNING_MESSAGE_EPISODERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reinforcement_learning
{
template <class ContainerAllocator>
struct EpisodeResult_
{
  typedef EpisodeResult_<ContainerAllocator> Type;

  EpisodeResult_()
    : reward(0.0)
    , length(0)  {
    }
  EpisodeResult_(const ContainerAllocator& _alloc)
    : reward(0.0)
    , length(0)  {
  (void)_alloc;
    }



   typedef float _reward_type;
  _reward_type reward;

   typedef int32_t _length_type;
  _length_type length;





  typedef boost::shared_ptr< ::reinforcement_learning::EpisodeResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reinforcement_learning::EpisodeResult_<ContainerAllocator> const> ConstPtr;

}; // struct EpisodeResult_

typedef ::reinforcement_learning::EpisodeResult_<std::allocator<void> > EpisodeResult;

typedef boost::shared_ptr< ::reinforcement_learning::EpisodeResult > EpisodeResultPtr;
typedef boost::shared_ptr< ::reinforcement_learning::EpisodeResult const> EpisodeResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reinforcement_learning::EpisodeResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reinforcement_learning::EpisodeResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace reinforcement_learning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'reinforcement_learning': ['/home/karel/Documents/University/WS2019/AAIP/software_integration/src/autonomous/reinforcement_learning/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::reinforcement_learning::EpisodeResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reinforcement_learning::EpisodeResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reinforcement_learning::EpisodeResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reinforcement_learning::EpisodeResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reinforcement_learning::EpisodeResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reinforcement_learning::EpisodeResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reinforcement_learning::EpisodeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa4f4b21e1c3537a9bf4795f8c325893";
  }

  static const char* value(const ::reinforcement_learning::EpisodeResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa4f4b21e1c3537aULL;
  static const uint64_t static_value2 = 0x9bf4795f8c325893ULL;
};

template<class ContainerAllocator>
struct DataType< ::reinforcement_learning::EpisodeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reinforcement_learning/EpisodeResult";
  }

  static const char* value(const ::reinforcement_learning::EpisodeResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reinforcement_learning::EpisodeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 reward\n"
"int32 length\n"
;
  }

  static const char* value(const ::reinforcement_learning::EpisodeResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reinforcement_learning::EpisodeResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reward);
      stream.next(m.length);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EpisodeResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reinforcement_learning::EpisodeResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reinforcement_learning::EpisodeResult_<ContainerAllocator>& v)
  {
    s << indent << "reward: ";
    Printer<float>::stream(s, indent + "  ", v.reward);
    s << indent << "length: ";
    Printer<int32_t>::stream(s, indent + "  ", v.length);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REINFORCEMENT_LEARNING_MESSAGE_EPISODERESULT_H
