
int16 linearspeed   #Linear Speed or right or left speed with angle
int16 motor1_speed #Individual Speed info from each motor
int16 motor2_speed
int16 motor3_speed
int16 motor4_speed
int16 motor5_speed
int16 motor6_speed
int16 motor1_current
int16 motor2_current
int16 motor3_current
int16 motor4_current
int16 motor5_current
int16 motor6_current
int16 voltage  #Battery voltage reading and temperature
int16 temperature